---
title: "Drinking Age leaflet"
author: "Nana Boame"
date: "December 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# clean age data
age <- readRDS("C:/Users/akosu/Desktop/final-project-etsyscrape/Shiny-App/age data/min_age_table.rds")

# rename columns
names(age)
colnames(age) <- c("Country", "On Premise", "Off Premise")

# delete first row of data as it is a duplicate of column names
age <- age[-1,]

# within each column, remove * [ ]
age$`On Premise` <- gsub("[*]", "", age$`On Premise`)
age$`Off Premise` <- gsub("[*]", "", age$`Off Premise`)

age$Country <- as.character(age$Country)
age <- as.data.frame(age)

# add lat long data to each country
install.packages("ggmap")
library(ggmap)

countrylatlon <- as.data.frame(geocode(age$Country, output = "latlon", source = "dsk"))

min_age_table_clean <- saveRDS("age", "C:/Users/akosu/Desktop/final-project-etsyscrape/Shiny-App/age data/min_age_table_clean.rds")
```



```{r}
install.packages("leaflet")
library(leaflet)

leaflet() %>%
  addTiles() %>%
  addProviderTiles("CartoDB")



age$Country %>%
  leaflet() %>%
  addTiles %>%
  addPolygons()

```

#fit the above into the below format

ui <- navbarPage(strong("TravelBeeR"),
           tabPanel("Legal Drinking Age",
                    sidebarLayout(
                      sidebarPanel(
                        dateInput("birthdate", "Enter your date of birth (yyyy-mm-dd): ")
                      ),
                      mainPanel(
                        leafletOutput("age_map"),
                        dataTableOutput("age_table")
                      )
                    )
           ),